#dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Through the data, darkly
tagline:             Exploring Society through numbers
description:         'Clayton Besaw is a PhD student in the Political Science department at the Univeristy of Central Florida. This site details his research and thoughts concerning politics, data-science, and everything in-between.'
url:                 cbesaw.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name: 'Clayton Besaw'
  email: 'claybesaw[at]gmail[dot]com'
  github: cbesaw
  stacko: http://stackoverflow.com/users/5748647/cbesaw
  google_scholar: https://scholar.google.com/citations?user=LOouXxgAAAAJ
  twitter: Clayton Besaw
  linkedin: clayton besaw
  
  

# Custom vars
version: 1.0

